import { useRouter } from "expo-router";
import React from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { dimensions, radii, spacing, typeScale } from "@nuttie/design-tokens";

import { Icon, type IconName } from "../../src/components/Icon";
import { Screen } from "../../src/components/Screen";
import { useAppStore } from "../../src/state/useAppStore";
import { useAppTheme } from "../../src/theme";

export default function SettingsScreen() {
  const { colors } = useAppTheme();
  const router = useRouter();
  const session = useAppStore((state) => state.session);
  const queue = useAppStore((state) => state.queue);
  const lastSyncError = useAppStore((state) => state.lastSyncError);
  const signOut = useAppStore((state) => state.signOut);
  const sync = useAppStore((state) => state.sync);
  const authenticated = session?.mode === "authenticated";
  return <Screen><View style={styles.header}><Text style={[styles.kicker, { color: colors.inkMuted }]}>设置</Text><Text style={[styles.title, { color: colors.ink }]}>让边界也清清楚楚</Text><Text style={[styles.body, { color: colors.inkMuted }]}>账号与同步是可选的产品能力；记录、来源和删除权利始终由你掌握。</Text></View><View style={[styles.account, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.chestnut }]}><Icon name="user" size={21} color={colors.inverse} /></View><View style={styles.accountCopy}><Text style={[styles.accountName, { color: colors.ink }]}>{authenticated ? session.user.displayName : "本地演示用户"}</Text><Text style={[styles.accountEmail, { color: colors.inkMuted }]}>{authenticated ? session.user.email : "尚未登录 · 数据仅保存在本机"}</Text></View><View style={[styles.statusDot, { backgroundColor: authenticated ? colors.sprout : colors.amber }]} /></View><View style={styles.group}><Text style={[styles.groupTitle, { color: colors.inkMuted }]}>同步</Text><SettingRow icon="cloud" title="云端同步" detail={authenticated ? queue.length ? `${queue.length} 条记录等待上传` : "已连接，最近一次同步正常" : "登录后开启，多设备共享同一份历史"} tone={authenticated ? "sprout" : "amber"} onPress={() => void sync()} /><SettingRow icon="refresh" title="立即同步" detail={lastSyncError ?? "手动触发一次拉取与队列重放"} tone={lastSyncError ? "danger" : "sky"} onPress={() => void sync()} /></View><View style={styles.group}><Text style={[styles.groupTitle, { color: colors.inkMuted }]}>个人数据</Text><SettingRow icon="user" title="档案与目标" detail="个人目标将在档案能力接入后开放" tone="chestnut" /><SettingRow icon="cloud" title="导出与删除" detail="数据导出与删除将在账户数据工具接入后开放" tone="sky" /></View><View style={styles.group}><Text style={[styles.groupTitle, { color: colors.inkMuted }]}>隐私边界</Text><View style={[styles.notice, { backgroundColor: colors.sproutSoft, borderColor: colors.border }]}><Icon name="leaf" size={19} color={colors.sprout} /><Text style={[styles.noticeText, { color: colors.ink }]}>不使用广告、行为分析或远程推送。AI 只在你主动确认后发送，API key 不会进入云同步。</Text></View></View>{authenticated && <Pressable accessibilityRole="button" onPress={() => void signOut().then(() => router.replace("/sign-in"))} style={({ pressed }) => [styles.logout, { borderColor: colors.border }, pressed && { opacity: 0.7 }]}><Icon name="logout" size={18} color={colors.danger} /><Text style={[styles.logoutText, { color: colors.danger }]}>退出登录</Text></Pressable>}</Screen>;
}

function SettingRow({ icon, title, detail, tone, onPress }: { icon: IconName; title: string; detail: string; tone: "sprout" | "amber" | "chestnut" | "sky" | "danger"; onPress?: () => void }) { const { colors } = useAppTheme(); const iconColor = tone === "sky" ? colors.skyDark : colors[tone]; const content = <><View style={[styles.rowIcon, { backgroundColor: tone === "sprout" ? colors.sproutSoft : tone === "amber" ? colors.amberSoft : tone === "sky" ? colors.skySoft : tone === "danger" ? colors.dangerSoft : colors.amberSoft }]}><Icon name={icon} size={18} color={iconColor} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: colors.ink }]}>{title}</Text><Text style={[styles.rowDetail, { color: colors.inkMuted }]}>{detail}</Text></View>{onPress && <Icon name="next" size={18} color={colors.inkMuted} />}</>; if (!onPress) return <View accessibilityRole="text" style={[styles.row, { backgroundColor: colors.surface, borderColor: colors.border, opacity: 0.82 }]}>{content}</View>; return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.75 }]}>{content}</Pressable>; }

const styles = StyleSheet.create({ header: { gap: spacing.sm }, kicker: { ...typeScale.caption, fontWeight: "700" }, title: { ...typeScale.title }, body: { ...typeScale.body, lineHeight: 22 }, account: { minHeight: 80, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.card, padding: spacing.lg, flexDirection: "row", alignItems: "center", gap: spacing.md }, avatar: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, accountCopy: { flex: 1, minWidth: 0, gap: 3 }, accountName: { ...typeScale.body, fontWeight: "700" }, accountEmail: { ...typeScale.caption }, statusDot: { width: 10, height: 10, borderRadius: 5 }, group: { gap: spacing.sm }, groupTitle: { ...typeScale.caption, fontWeight: "700" }, row: { minHeight: 72, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.compact, padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.md }, rowIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1, minWidth: 0, gap: 2 }, rowTitle: { ...typeScale.body, fontWeight: "700" }, rowDetail: { ...typeScale.caption }, notice: { minHeight: 76, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.compact, padding: spacing.md, flexDirection: "row", alignItems: "flex-start", gap: spacing.sm }, noticeText: { ...typeScale.body, flex: 1, lineHeight: 22 }, logout: { minHeight: dimensions.control, borderWidth: 1, borderRadius: radii.compact, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm }, logoutText: { ...typeScale.label },
});
