import React, { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { dimensions, radii, spacing, typeScale } from "@nuttie/design-tokens";

import { Screen } from "../../src/components/Screen";
import { useAppStore } from "../../src/state/useAppStore";
import { useAppTheme } from "../../src/theme";
import { useResponsiveLayout } from "../../src/hooks/useResponsiveLayout";

type Metric = "摄入" | "饮水" | "体重";
const metricOptions: Metric[] = ["摄入", "饮水", "体重"];
const sampleDays = ["周一", "周二", "周三", "周四", "周五", "周六", "今天"];

export default function TrendsScreen() {
  const { width } = useResponsiveLayout();
  const wide = width >= 768;
  const { colors } = useAppTheme();
  const records = useAppStore((state) => state.records);
  const [metric, setMetric] = useState<Metric>("摄入");
  const meals = records.filter((record) => record.kind === "meal");
  const water = records.filter((record) => record.kind === "water");
  const weight = records.find((record) => record.kind === "weight")?.amount;
  const todayValue = metric === "摄入" ? meals.reduce((sum, record) => sum + (record.energyKcal ?? 0), 0) : metric === "饮水" ? water.reduce((sum, record) => sum + (record.amount ?? 0), 0) : weight ?? 0;
  const values = useMemo(() => sampleDays.map((_, index) => index === sampleDays.length - 1 ? todayValue : 0), [todayValue]);
  const max = Math.max(...values, metric === "体重" ? 1 : 100);
  const summary = todayValue ? `今天${metric} ${metric === "体重" ? `${todayValue.toFixed(1)} kg` : `${Math.round(todayValue)}${metric === "摄入" ? " kcal" : " ml"}`}` : `今天还没有${metric}记录`;
  return <Screen><View style={styles.header}><View><Text style={[styles.kicker, { color: colors.inkMuted }]}>最近 7 天</Text><Text style={[styles.title, { color: colors.ink }]}>看见趋势，不急着下结论</Text></View></View><View style={[styles.switcher, { backgroundColor: colors.surfaceMuted }]}>{metricOptions.map((item) => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: metric === item }} onPress={() => setMetric(item)} style={[styles.switchItem, metric === item && { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.switchText, { color: metric === item ? colors.ink : colors.inkMuted }]}>{item}</Text></Pressable>)}</View><View style={[styles.layout, wide && styles.layoutWide]}><View style={[styles.chartPanel, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.panelHeading}><View><Text style={[styles.panelTitle, { color: colors.ink }]}>{metric}记录</Text><Text style={[styles.panelCaption, { color: colors.inkMuted }]}>按已保存的本地数据展示</Text></View><Text style={[styles.unit, { color: colors.inkMuted }]}>{metric === "摄入" ? "kcal" : metric === "饮水" ? "ml" : "kg"}</Text></View><View accessibilityRole="image" accessibilityLabel={`${metric}七日图，${summary}`} style={styles.chart}>{values.map((value, index) => <View key={sampleDays[index]} style={styles.barColumn}><View style={styles.barTrack}><View style={[styles.bar, { height: `${Math.max(4, (value / max) * 100)}%`, backgroundColor: metric === "摄入" ? colors.chestnut : metric === "饮水" ? colors.skyDark : colors.sprout }]} /></View><Text style={[styles.day, { color: colors.inkMuted }]}>{sampleDays[index]}</Text><Text style={[styles.barValue, { color: colors.ink }]}>{value ? Math.round(value) : "—"}</Text></View>)}</View></View><View style={[styles.insightPanel, { backgroundColor: colors.surfaceMuted, borderColor: colors.border }]}><Text style={[styles.panelTitle, { color: colors.ink }]}>文字摘要</Text><Text style={[styles.summary, { color: colors.ink }]}>{summary}</Text><Text style={[styles.detail, { color: colors.inkMuted }]}>只有今天有记录时，其他日期会保持空白。空白代表没有数据，不代表没有发生。</Text><View style={[styles.legend, { borderTopColor: colors.border }]}><View style={[styles.legendDot, { backgroundColor: colors.sprout }]} /><Text style={[styles.legendText, { color: colors.inkMuted }]}>数据来源：手工记录 / 本地缓存</Text></View></View></View><View style={[styles.note, { backgroundColor: colors.amberSoft, borderColor: colors.border }]}><Text style={[styles.noteTitle, { color: colors.ink }]}>关于趋势</Text><Text style={[styles.noteBody, { color: colors.inkMuted }]}>趋势页帮助你回看自己的记录，不提供医疗判断，也不会替你设定目标。</Text></View></Screen>;
}

const styles = StyleSheet.create({ header: { gap: spacing.xs }, kicker: { ...typeScale.caption, fontWeight: "700" }, title: { ...typeScale.title, marginTop: 3 }, switcher: { minHeight: 48, borderRadius: radii.compact, padding: 4, flexDirection: "row", gap: 4 }, switchItem: { minHeight: dimensions.minTouch, flex: 1, borderRadius: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: "transparent", alignItems: "center", justifyContent: "center" }, switchText: { ...typeScale.label }, layout: { gap: spacing.lg }, layoutWide: { flexDirection: "row", alignItems: "stretch" }, chartPanel: { flex: 1, minHeight: 340, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.card, padding: spacing.lg, gap: spacing.xl }, insightPanel: { flex: 0.72, minHeight: 220, borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.card, padding: spacing.lg, gap: spacing.md }, panelHeading: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, panelTitle: { ...typeScale.heading }, panelCaption: { ...typeScale.caption, marginTop: 3 }, unit: { ...typeScale.caption }, chart: { flex: 1, minHeight: 220, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: spacing.sm }, barColumn: { flex: 1, alignItems: "center", justifyContent: "flex-end", gap: 4, minWidth: 28 }, barTrack: { width: "100%", maxWidth: 34, height: 160, justifyContent: "flex-end", borderRadius: 8, backgroundColor: "rgba(127,129,120,0.12)", overflow: "hidden" }, bar: { width: "100%", minHeight: 4, borderRadius: 8 }, day: { ...typeScale.caption, fontSize: 11 }, barValue: { ...typeScale.caption, fontWeight: "700" }, summary: { ...typeScale.title, fontSize: 22, lineHeight: 28 }, detail: { ...typeScale.body, lineHeight: 22 }, legend: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: "auto" }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { ...typeScale.caption }, note: { borderWidth: StyleSheet.hairlineWidth, borderRadius: radii.compact, padding: spacing.lg, gap: spacing.xs }, noteTitle: { ...typeScale.label, fontWeight: "700" }, noteBody: { ...typeScale.body, lineHeight: 22 },
});
